# Generated by Django 2.2 on 2023-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='leftpanel',
            name='order',
            field=models.IntegerField(default='0', max_length=20),
        ),
    ]
