# Generated by Django 2.2 on 2023-09-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0002_auto_20230926_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='price',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicare.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='timing',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
