# Generated by Django 2.2 on 2023-09-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0003_auto_20230917_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(max_length=50, null=True)),
                ('deleted_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Instrictions',
            },
        ),
        migrations.CreateModel(
            name='Medicalhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=40, null=True)),
                ('height', models.CharField(max_length=40, null=True)),
                ('weight', models.CharField(max_length=40, null=True)),
                ('alcoholic', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('deleted_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Medical_history',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Prescriptinons_details',
            },
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructuns',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
