# Generated by Django 2.2 on 2023-09-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0005_auto_20230920_1802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leftpanel',
            table='Leftpannel',
        ),
    ]
