# Generated by Django 2.2 on 2023-09-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0005_auto_20230928_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicare.Patient'),
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=50, null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicare.Doctor')),
            ],
            options={
                'db_table': 'avialable_slots',
            },
        ),
    ]
