# Generated by Django 2.2 on 2023-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0007_appointment_doct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doct',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
