# Generated by Django 2.2 on 2023-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0007_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
    ]
