# Generated by Django 2.2 on 2023-09-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0008_auto_20230921_1832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructuns',
            table='Instructions',
        ),
    ]
