# Generated by Django 2.2 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0008_role_deleted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
