# Generated by Django 2.2 on 2023-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0010_auto_20230923_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
