# Generated by Django 2.2 on 2023-09-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0012_auto_20230923_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftpanel',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='leftpanel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicare.Role'),
        ),
    ]
